name: CI

on:
  push:
    branches:
      - main
      - master
  pull_request: {}

concurrency:
   group: ci-${{ github.head_ref || github.ref }}
   cancel-in-progress: true

env:
  TURBO_API: http://127.0.0.1:9080
  TURBO_TOKEN: this-is-not-a-secret
  TURBO_TEAM: myself

jobs:
  setup:
    name: 'Setup'
    runs-on: ubuntu-latest
    outputs:
      pending: ${{ steps.set-pending.outputs.pend }}
    steps:
      - uses: wyvox/action@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - run: pnpm build
      # Determine which of the next jobs need to run
      - id: set-pending
        run: |
          todos=$(pnpm -w exec ci-todo)
          echo $todos | jq
          echo "pend=$todos" >> $GITHUB_OUTPUT
      - run:  echo ${{ github.event.number }} > ./pr-number.txt

  # debug_pending_tasks:
  #   runs-on: ubuntu-latest
  #   needs: [setup]
  #   steps:
  #     - run: echo ${{  needs.setup.outputs.pending }}
  #     - run: echo '${{  needs.setup.outputs.pending }}' | jq
  #     - run: echo '${{  fromJSON(needs.setup.outputs.pending).atAll.lint }}'

  lint:
    name: Lint
    runs-on: ubuntu-latest
    needs: [setup]
    if: ${{ fromJSON(needs.setup.outputs.pending).atAll.lint }}
    steps:
      - uses: wyvox/action@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - run: pnpm lint


  test:
    name: "Default Tests"
    runs-on: ubuntu-latest
    needs: [setup]
    if: ${{ fromJSON(needs.setup.outputs.pending).atAll.test }}
    steps:
      - uses: wyvox/action@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - run: pnpm test --filter test-app

  floating:
    name: "Floating Dependencies"
    runs-on: ubuntu-latest
    needs: [test]
    if: ${{ fromJSON(needs.setup.outputs.pending).atAll.test }}
    steps:
      - uses: wyvox/action@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          pnpm-args: --no-lockfile
      - run: pnpm test --filter test-app

  try-scenarios:
    name: ${{ matrix.try-scenario }}
    runs-on: ubuntu-latest
    needs: [test]
    if: ${{ fromJSON(needs.setup.outputs.pending).atAll.test }}
    strategy:
      fail-fast: false
      matrix:
        try-scenario:
          - ember-lts-4.8
          - ember-lts-4.12
          - ember-5.0
          - ember-release
          - ember-beta
          - ember-canary
          - embroider-safe
          - embroider-optimized

    steps:
      - uses: wyvox/action@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Run Tests
        run: ./node_modules/.bin/ember try:one ${{ matrix.try-scenario }} --skip-cleanup
        working-directory: test-app

  typecheck:
    name: '${{ matrix.typescript-scenario }}'
    runs-on: ubuntu-latest
    if: ${{ fromJSON(needs.setup.outputs.pending).atAll.typecheck }}
    timeout-minutes: 2
    needs: [test]
    continue-on-error: true
    strategy:
      fail-fast: true
      matrix:
        typescript-scenario:
          - typescript@4.8
          - typescript@4.9
          - typescript@5.0
          - typescript@rc
          - typescript@next

    steps:
      - uses: wyvox/action@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - name: 'Change TS to ${{ matrix.typescript-scenario }}'
        run: 'pnpm add --save-dev ${{ matrix.typescript-scenario}}'
        working-directory: ./test-app
      - name: 'Type checking'
        run: pnpm turbo --filter 'test-app' lint:types

  docs-tests:
    name: 'Docs Tests'
    if: ${{ fromJSON(needs.setup.outputs.pending).tests.docs-app }}
    runs-on: ubuntu-latest
    needs: [setup]
    steps:
      - uses: wyvox/action@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - run: pnpm test --filter docs-app

  docs-types:
    name: 'Docs Tests'
    if: ${{ fromJSON(needs.setup.outputs.pending).tests.docs-app }}
    runs-on: ubuntu-latest
    needs: [setup]
    steps:
      - uses: wyvox/action@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - run: pnpm lint:types --filter docs-app

  # https://github.com/changesets/action
  release:
    name: Release
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    timeout-minutes: 15
    needs: [typecheck, try-scenarios]
    permissions:
      contents: write
      packages: write
      pull-requests: write
    steps:
      - uses: wyvox/action@v1
      - name: Create Release Pull Request or Publish to npm
        id: changesets
        uses: changesets/action@v1
        with:
          publish: pnpm release
          title: "Release Preview"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}



